### ISSUE TITLE
on hover not working

### ISSUE THREAD

**Issue by anmol27katyani** [saranshbarua/saranshbarua.github.io#5]
onHover is not working on the Safari Web Browser.

**Comment by saranshbarua** [comment]
@octamois thanks for reporting the issue. Can you help me with the work-around for this? I don't have safari browser, so can you open the dev-tools and do some magic?
[link that may help](https://stackoverflow.com/questions/35187970/css-hover-not-working-on-ios-safari-and-chrome)

**Comment by octamois** [comment]
I will surely put a PR with correction @saranshbarua .

**Comment by saranshbarua** [comment]
I tested it on safari and other browsers. It's working fine. Closing this.
